### ISSUE TITLE
Cannot run Spoon on particular Test Class when declared in afterEvaluate

### ISSUE THREAD

**Issue by fahimsakri** [stanfy/spoon-gradle-plugin#94]
Cannot run a particular test case when declared afterEvaluate in build gradle, 

```
afterEvaluate {
        apply plugin: 'spoon'
        spoon {
            // for debug output
            debug = true
            adbTimeout = 60
            className = 'com.junit.suite.JunitTestSuite'
        }
    }
```

It works propery when i dont use afterEvaluate. 
How can i fix this?

**Comment by originx** [comment]
I have the same issue, we have apk renaming for our project so we need to apply spoon after evaluation.
It seems that config setting is completely ignored if used in afterEvaluate, is there any way around this?

**Comment by vase4kin** [comment]
Hello, guys, any updates?

**Comment by cmatulessy** [comment]
Is there still any support for this question? I have the same issue with Spoon for this.

**Comment by roman-mazur** [comment]
The problem is that when plugin is applied, it adds hooks on every test variant to create spoon tasks. When you apply it in `afterEvaluate`, test variants are already created and plugin code is executed immediately (before spoon config is changed).

If you deal with a case described by @originx, you might try putting `apply plugin: 'spoon'` after you add closures that modify application variants. So, instead of using `afterEvaluate`, you just do
```groovy
application.variants.all { variant ->
  // rename apk...
}
apply plugin: 'spoon'
spoon {
  // edit the config
}
```

It should work for this particular case.

**Comment by cmatulessy** [comment]
Thanks @roman-mazur this works for me 👍 and also thanks for the quick response

**Comment by cmatulessy** [comment]
@roman-mazur Today I was switching branches and came back to my branch with the spoon gradle plugin. And I got the same error again.

I was investigating this and I saw that if you first out comment the application.variants.all it will generate the standard app name apk spoon is working with. (so this works) After I uncomment the application.variants.all the tests are running again, but because the standard apk is already generated this will of course work, If I delete it and rerun than I got the same error that it could not find the apk.

So to summarise the issue:

**This doesn't work with fresh install:**
```
application.variants.all { variant ->
  // rename apk...
}

apply plugin: 'spoon'
spoon {
  // edit the config
}
```

**This works:**
_Step 1:_
```
//application.variants.all { variant ->
// rename apk...
//}

apply plugin: 'spoon'
spoon {
  // edit the config
}
```

**Run the application.**

_Step 2:_
```
application.variants.all { variant ->
  // rename apk...
}

apply plugin: 'spoon'
spoon {
  // edit the config
}
```

**Rerun the application**

Any clue or idea for this?
